// week-02.a-vue/project/src/components/ui/SocialLink.vue
<script setup>
defineProps({
  href: {
    type: String,
    required: true
  },
  label: {
    type: String,
    required: true
  },
  iconClassName: {
    type: String,
    required: true
  }
});
</script>

<template>
  <a class="w-9 h-9 flex justify-center items-center rounded-full border border-slate-800 text-slate-500 hover:text-slate-50 hover:border-violet-500 transition" :href="href" :aria-label="label" target="_blank" rel="noopener noreferrer">
    <i :class="iconClassName"></i>
  </a>
</template>

// week-02-svelte/project/src/components/ui/SocialLink.svelte
<script>
  let { href, label, iconClassName } = $props();
</script>

<a class="w-8 h-8 flex flex-row justify-center items-center rounded-md border border-slate-800 bg-slate-950 hover:bg-violet-500 shadow-xl shadow-slate-950/40 hover:shadow-violet-500/40 transition" {href} target="_blank" rel="noopener noreferrer" aria-label={label}>
  <i class={iconClassName}></i>
</a>
