// week-02-vue/project/src/components/ui/SectionTitle.vue
<script setup>
import { computed } from "vue";

const props = defineProps({
  highlight: {
    type: String,
    required: true
  },
  size: {
    type: String,
    default: "default"
  }
});

const titleClassName = computed(function () {
  if (props.size === "large") {
    return "text-5xl md:text-7xl font-black tracking-tight leading-none";
  }

  return "text-4xl md:text-5xl font-black tracking-tight leading-tight";
});
</script>

<template>
  <h2 :class="titleClassName">
    <slot></slot>
    <span class="block text-violet-300">{{ highlight }}</span>
  </h2>
</template>

// week-01-react/project/src/components/ui/SectionTitle.jsx
function SectionTitle({ children, highlight, size = "default" }) {
    let className = "max-w-4xl font-black tracking-tight leading-none";

    if (size === "default") {
        className += " text-4xl md:text-5xl";
    }

    if (size === "large") {
        className += " text-5xl md:text-7xl";
    }

    return (
        <h2 className={className}>
            {children}

            <span className="block text-violet-300">
                {highlight}
            </span>
        </h2>
    );
}

export default SectionTitle;
